name: empatica_e4link
description: Flutter plugin for the Empatica E4 wristband
version: 0.1.0
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/empatica_e4link

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: dk.cachet.empatica_e4link
        pluginClass: EmpaticaFlutterPlugin
