name: empatica_e4link_example
description: Demonstrates how to use the empatica_e4link plugin.
publish_to: "none"

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  flutter_background: ^1.1.0
  empatica_e4link:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
