name: app_usage
description: App usage plugin for Android only
version: 2.1.1
homepage: https://github.com/cph-cachet/flutter-plugins/blob/master/packages/app_usage

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dk.cachet.app_usage
        pluginClass: AppUsagePlugin
